#!/bin/bash

# Récupère les infos de l'application.
app=radicale
final_path=$(sudo yunohost app setting $app final_path)
domain=$(sudo yunohost app setting $app domain)

ynh_abort_if_errors
# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/$app
sudo mkdir -p "$backup_dir"

# Backup sources & data
cp -a $final_path/. $backup_dir/sources
cp -a /home/$app/. $backup_dir/data
# Copy Nginx and YunoHost parameters to make the script "standalone"
cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf

# Copy radicale configuration
cp -a /etc/$app/. $backup_dir/etc

# Copie la configuration de logrotate
cp -a /etc/logrotate.d/$app $backup_dir/logrotate
