#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC
app=$YNH_APP_INSTANCE_NAME
version=$(ynh_app_upstream_version)

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================
ynh_print_info "Validating installation parameters ..."
data_user="/home/$app"
test ! -e "$data_user" || ynh_die "The user data path $data_user already contains a folder."

final_path="/opt/yunohost/$app"
test ! -e "$final_path" || ynh_die "The application path $final_path already exists. Is $app already installed?"

config_path="/etc/$app"
test ! -e "$config_path" || ynh_die "The application path $config_path already exists. Is $app already installed?"

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path "$path_url")

# Register (book) web path
ynh_webpath_register "$app" "$domain" "$path_url"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_print_info "Storing installation settings..."

ynh_app_setting_set "$app" domain "$domain"
ynh_app_setting_set "$app" path "$path_url"
ynh_app_setting_set "$app" is_public "$is_public"
ynh_app_setting_set "$app" version "$version"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_print_info "Installing dependencies: ${pkg_dependencies}..."
ynh_install_app_dependencies "$pkg_dependencies"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_print_info "Creating a system user '${app}'..."
ynh_system_user_create "$app"

#=================================================
# SPECIFIC SETUP
#=================================================
# INSTALL RADICALE IN A VIRTUALENV
#=================================================
# Init virtualenv
ynh_print_info "Creating Python virtual environment for Radicale..."
virtualenv -p python3 "$final_path"
ynh_print_info "Installing Radicale ${version}..."
"$final_path/bin/pip3" install "radicale==$version" ldap3
ynh_print_info "Installing LDAP login support for Radicale..."
"$final_path/bin/pip3" install ../sources/marcoh00/radicale_auth_ldap

ynh_app_setting_set "$app" final_path "$final_path"

ynh_print_info "Creating user data directory '${data_user}'..."
mkdir -p "$data_user"
chown -R "$app": "$data_user"
ynh_app_setting_set "$app" data_user "$data_user"

#=================================================
# CONFIGURE RADICALE
#=================================================
ynh_print_info "Writing configuration settings..."
mkdir -p "$config_path"
cp ../conf/config "$config_path"
cp ../conf/logging "$config_path"
cp ../conf/radicale.env "$config_path"

ynh_replace_string "__FINALPATH__" "$final_path" "$config_path/radicale.env"
ynh_replace_string "__PATH__" "${path_url%/}" "$config_path/config"
ynh_replace_string "__DATA_USER__" "$data_user" "$config_path/config"
ynh_replace_string "__CONFIG_PATH__" "$config_path" "$config_path/config"
ynh_replace_string "__APP__" "$app" "$config_path/logging"

ynh_store_file_checksum "$config_path/config"
ynh_store_file_checksum "$config_path/logging"
ynh_store_file_checksum "$config_path/radicale.env"

# Set permissions to radicale directory
chown root: -R "$final_path"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_print_info "Configuring a systemd service $app"
ynh_add_systemd_config -v "data_user config_path"

#=================================================
# NGINX CONFIGURATION
#=================================================
# Modify Nginx configuration file and copy it to Nginx conf directory
ynh_print_info "Configuring nginx web server..."
ynh_replace_string "__PATH__" "$path_url" ../conf/nginx.conf
ynh_add_nginx_config

# Fix permission
chmod 755 "$config_path/"
find "/opt/yunohost/$app/" -type d -exec chmod 2755 {} \;
find "/opt/yunohost/$app/" -type f -exec chmod g+r,o+r {} \;
chmod 644 "$config_path/"*

yunohost service add "$app"

# Configuration ssowat
ynh_print_info "Configuring permissions..."
if [ "$is_public" -eq 1 ]; then
  ynh_print_info "Permitting unauthorized users to access the app..."
  ynh_permission_update --permission "main" --add visitors
fi

#=================================================
# HOOKS FOR CREATE USER AND REMOVE
#=================================================
ynh_replace_string "__DATA_USER__" "$data_user" ../hooks/post_user_delete

#Add service radicale
ynh_print_info "Starting service $app..."
systemctl enable "$app"
yunohost service start "$app"

#=================================================
# RELOAD NGINX
#=================================================
ynh_print_info "Reloading nginx web server..."
service nginx reload


