#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers
# Load common variables for all scripts.
source _variables

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.


#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH

app=$YNH_APP_INSTANCE_NAME

version=$(grep '\"version\": ' ../manifest.json | cut -d '"' -f 4 | cut -d '~' -f 1)	# Retrieve the version number in the manifest file.

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================

# Vérifie que le dossier de destination n'est pas déjà utilisé.
final_path=/home/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

app_path=/opt/yunohost/$app

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path $path_url)

# Check web path availability
ynh_webpath_available $domain $path_url
# Register (book) web path
ynh_webpath_register $app $domain $path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path_url
ynh_app_setting_set $app version $version


#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_install_app_dependencies $app_depencencies

#=================================================
# NGINX CONFIGURATION
#=================================================
# Modify Nginx configuration file and copy it to Nginx conf directory

ynh_add_nginx_config
ynh_store_file_checksum "$finalnginxconf"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_system_user_create $app	# Créer un utilisateur système dédié à l'app

#=================================================
# SPECIFIC SETUP
#=================================================
# INSTALL RADICALE IN A VIRTUALENV
#=================================================
# Init virtualenv
sudo virtualenv -p python3 /opt/yunohost/$app
sudo $app_path/bin/pip install 'radicale==2.1.8' ldap3
sudo $app_path/bin/pip install ../sources/ajouts_radicale/ynh_ldap_auth/

#=================================================
# COPY FILES INTO $FINAL_PATH
#=================================================
# Crée le repertoire de destination et stocke son emplacement.
mkdir "$final_path"
ynh_app_setting_set $app final_path $final_path

#=================================================
# CONFIGURE RADICALE
#=================================================
#Configuration Radicale
sudo mkdir -p /etc/$app
sudo cp ../conf/config /etc/$app/
sudo cp ../conf/logging /etc/$app/

sudo cp ../conf/logrotate /etc/logrotate.d/$app
sudo cp ../conf/radicale.env /etc/$app/


ynh_replace_string "__APP_PATH__" "$app_path" /etc/$app/radicale.env
ynh_replace_string "__PATH__" "${path_url%/}" /etc/$app/config
ynh_replace_string "__FINALPATH__" "$final_path" /etc/$app/config

# Enregistre la somme de contrôle du fichier de config
ynh_store_file_checksum "/etc/$app/config"
ynh_store_file_checksum "/etc/$app/logging"
ynh_store_file_checksum "/etc/$app/radicale.env"

# Set permissions to radicale directory
sudo chown radicale: -R $app_path

# Set permissions to radicale directory
sudo chown -R radicale: $final_path
sudo mkdir /var/log/$app
sudo touch /var/log/$app/$app.log
sudo chown radicale -R /var/log/$app

ynh_replace_string "__FINALPATH__" "$final_path" ../hooks/post_user_delete

#Ajout du service radicale

sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo cp ../conf/radicale.service /etc/systemd/system/$app.service

ynh_replace_string "__APP_PATH__" "$app_path" /etc/systemd/system/$app.service
ynh_replace_string "__FINALPATH__" "$final_path" /etc/systemd/system/$app.service

# Fix permission
sudo chmod 755 /etc/$app/
sudo find /opt/yunohost/$app/ -type d -exec chmod 2755 {} \;
sudo find /opt/yunohost/$app/ -type f -exec chmod g+r,o+r {} \;
sudo chmod 644 /etc/$app/*


# Depuis radicale 2.0 chaque utilisateurs se créé son carnet d'adresse
# et ses calendriers depuis l'interface web accessible depuis /radicale/.web.
#=================================================
# SETUP LOGROTATE
#=================================================

ynh_use_logrotate

## Reload Nginx and regenerate SSOwat conf
sudo service nginx reload


# Configuration ssowat
sudo yunohost app setting $app unprotected_uris -v "/"    # Radicale est accessible librement (pour l'accès distant aux ressources)

sudo yunohost app ssowatconf


#Ajout de service radicale
sudo yunohost service add $app
sudo systemctl enable $app
sudo yunohost service start $app


#=================================================
# PREPARE THE HOOKS
#=================================================

# Modification des hook pour la création des collections par défaut des nouveaux utilisateurs. Et leur suppression
ynh_replace_string "__FINALPATH__" "$final_path" ../hooks/post_user_delete
