#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading installation settings before deinstallation..."
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain) # Do not remove! It is implicitly used by YunoHost commands.

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================
if yunohost service status "$app" >/dev/null 2&>1
then
	ynh_print_info "Removing $app service"
	yunohost service remove "$app"
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_print_info "Stopping and removing the systemd service"
ynh_remove_systemd_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_print_info "Removing dependencies"
ynh_remove_app_dependencies

#=================================================
# REMOVE THE MAIN DIR OF THE APP
#=================================================
ynh_print_info "Removing app main directory"
ynh_secure_remove "/opt/yunohost/$app"

ynh_print_info "Removing users data directory"
ynh_secure_remove "/home/$app"

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================
ynh_print_info "Removing nginx web server configuration"
ynh_remove_nginx_config

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE RADICALE'S CONFIG
#=================================================
ynh_print_info "Removing $app confiuration"
ynh_secure_remove "/etc/$app"

#=================================================
# GENERIC FINALISATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_print_info "Removing the dedicated system user"
ynh_system_user_delete "$app"

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info "Removal of $app completed"

