#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers
#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME
path_url=$(ynh_app_setting_get "$app" path)
final_path=$(ynh_app_setting_get "$app" final_path)
domain=$(ynh_app_setting_get "$app" domain)
data_user=$(ynh_app_setting_get "$app" data_user)

ynh_abort_if_errors

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================
ynh_print_info "Validating restoration parameters..."

ynh_webpath_available "$domain" "$path_url" \
		|| ynh_die "Path not available: ${domain}${path_url}"
test ! -d "$final_path" \
		|| ynh_die "There is already a directory: $final_path "

ynh_print_info "Restoring nginx configuration..."
ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_print_info "Restoring the app main directory..."
ynh_restore_file "$final_path"

ynh_print_info "Restoring the data directory..."
ynh_restore_file "$data_user"

ynh_print_info "Recreating the dedicated system user..."
ynh_system_user_create "$app"

# Restore permissions on app files
chown -R root: "$final_path"
chown -R "$app:" "$data_user"

ynh_print_info "Recreating the app configuration..."
ynh_restore_file "/etc/$app"

ynh_print_info "Reinstalling dependencies..."
ynh_install_app_dependencies "$pkg_dependencies"

ynh_print_info "Restore the systemd configuration..."
ynh_restore_file "/etc/systemd/system/$app.service"
systemctl enable "$app.service"


#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================
mkdir "/var/log/$app"
chown "$app:" "/var/log/$app"
yunohost service add "$app" --log "/var/log/$app/$app.log"

ynh_print_info "Restoring the logrotate configuration..."
ynh_restore_file "/etc/logrotate.d/$app"

ynh_print_info "Reloading nginx web server and $app service..."
systemctl start "$app.service"
systemctl reload nginx

ynh_print_info "Restoring completed for $app"

