#!/bin/bash
app=radicale

# Get app settings
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)


# Check depends installation
sudo apt-get install -y python3-pip python3-virtualenv python3-dev libldap2-dev libsasl2-dev libssl-dev

sudo chown radicale: -R /opt/yunohost/$app

# Upgrade pip packages
sudo rm -Rf /opt/yunohost/$app

sudo virtualenv -p python3 /opt/yunohost/$app
sudo /opt/yunohost/$app/bin/pip install --upgrade radicale ldap3
sudo /opt/yunohost/$app/bin/pip install ../sources/ajouts_radicale/ynh_ldap_auth/



# Radicale configuration
sudo cp ../conf/config /etc/$app/
sudo cp ../conf/logging /etc/$app/

sudo cp ../conf/logrotate /etc/logrotate.d/$app
sudo cp ../conf/radicale.env /etc/$app/

# sudo cp ../conf/rights /etc/$app/
sudo sed -i "s@__APP_PATH__@/opt/yunohost/$app@g" /etc/$app/radicale.env
sudo sed -i "s@__PATH__@$path@g" /etc/$app/config
sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/$app/config

# Set permissions to radicale directory
sudo chown -R radicale: $final_path
sudo chown radicale -R /var/log/$app

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo sed -i "s@__PATH__@$path@g" ../conf/nginx.conf
sudo sed -i "s@__FINALPATH__@$final_path@g" ../conf/radicale.service
sudo sed -i "s@__APP_PATH__@/opt/yunohost/$app@g" ../conf/radicale.service

#Ajout du service radicale
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo cp ../conf/radicale.service /etc/systemd/system/$app.service

# Fix permission
sudo chmod 755 /etc/$app/
sudo find /opt/yunohost/$app/ -type d -exec chmod 2755 {} \;
sudo find /opt/yunohost/$app/ -type f -exec chmod g+r,o+r {} \;
sudo chmod 644 /etc/$app/*

sudo yunohost app setting $app unprotected_uris -v "/"	# Radicale est accessible librement (pour l'accès distant aux ressources)

sudo yunohost app ssowatconf
sudo systemctl restart $app
sudo systemctl nginx reload

sudo sed -i "s@__FINALPATH__@$final_path@g" ../hooks/post_user_delete
sudo yunohost hook add radicale ../hooks/post_user_delete
