#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
version=$(ynh_app_setting_get $app version)

#=================================================
# CHECK VERSION
#=================================================

ynh_abort_if_up_to_date


if [ -z "$version" ]
then
	version=$(grep '\"version\": ' ../manifest.json | cut -d '"' -f 4 | cut -d '~' -f 1)	# Retrieve the version number in the manifest file.
	ynh_app_setting_set $app version "$version"
fi

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors


# Enregistre la somme de contrôle du fichier de config
ynh_store_file_checksum "/etc/$app/config"
ynh_store_file_checksum "/etc/$app/logging"
ynh_store_file_checksum "/etc/$app/radicale.env"

# Set permissions to radicale directory
sudo chown radicale: -R $app_path

# Set permissions to radicale directory
sudo chown -R radicale: $final_path
sudo mkdir /var/log/$app
sudo touch /var/log/$app/$app.log
sudo chown radicale -R /var/log/$app

ynh_replace_string "__FINALPATH__" "$final_path" ../hooks/post_user_delete


#Ajout du service radicale
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo cp ../conf/radicale.service /etc/systemd/system/$app.service

# Fix permission
sudo chmod 755 /etc/$app/
sudo find /opt/yunohost/$app/ -type d -exec chmod 2755 {} \;
sudo find /opt/yunohost/$app/ -type f -exec chmod g+r,o+r {} \;
sudo chmod 644 /etc/$app/*


#Depuis radicale 2.0 chaque utilisateurs se créé son carnet d'adresse et ses calendriers depuis l'interface web accessible depuis /radicale/.web.
#=================================================
# SETUP LOGROTATE
#=================================================

ynh_use_logrotate

## Reload Nginx and regenerate SSOwat conf
sudo service nginx reload

# Configuration ssowat
sudo yunohost app setting $app unprotected_uris -v "/" 

sudo yunohost app ssowatconf




#============================================
# Systemd
#============================================

ynh_replace_string "__FINALPATH__" "$final_path" /etc/systemd/system/$app.service
ynh_replace_string "__APP_PATH__" "$app_path" /etc/systemd/system/$app.service

#Ajout de service radicale
sudo yunohost service add $app
sudo systemctl enable $app
sudo yunohost service start $app

#=================================================
# PREPARE THE HOOKS
#=================================================

# Modification des hook pour la création des collections par défaut des nouveaux utilisateurs. Et leur suppression
ynh_replace_string "__FINALPATH__" "$final_path" ../hooks/post_user_delete
